# -*- coding: utf-8 -*-
"""Dashboard Streamlit - MC240D5Y0801.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pawUDgP36Fl0FFgyPp8rteDKWfaTRd9X
"""

import pandas as pd
import streamlit as st
import matplotlib.pyplot as plt
import seaborn as sns
from wordcloud import WordCloud

#menload data
data = pd.read_csv('/content/drive/MyDrive/order_reviews_dataset.csv')
data.dropna(subset=['review_comment_message'], inplace=True)

#judul dashboardnya
st.title("Dashboard Analisis Ulasan Pesanan")

# Descriptive Statistics
st.subheader("Statistik Deskriptif")
st.write(data['review_score'].describe())

#distribusi dari review_score nya
st.subheader("Distribusi Skor Ulasan")
fig, ax = plt.subplots()
sns.countplot(x='review_score', data=data, ax=ax)
ax.set_title('Distribusi Skor Ulasan')
ax.set_xlabel('Skor Ulasan')
ax.set_ylabel('Jumlah Ulasan')
st.pyplot(fig)

#menganalisis sentimen
data['sentiment'] = data['review_score'].apply(lambda x: 'positif' if x >= 4 else 'negatif')

# Word Cloud untuk review positif
st.subheader("Word Cloud - Ulasan Positif")
positive_reviews = ' '.join(data[data['sentiment'] == 'positif']['review_comment_message'])
wordcloud_positive = WordCloud(width=800, height=400, background_color='white').generate(positive_reviews)
fig, ax = plt.subplots()
ax.imshow(wordcloud_positive, interpolation='bilinear')
ax.axis('off')
st.pyplot(fig)

# Word Cloud untuk review negatif
st.subheader("Word Cloud - Ulasan Negatif")
negative_reviews = ' '.join(data[data['sentiment'] == 'negatif']['review_comment_message'])
wordcloud_negative = WordCloud(width=800, height=400, background_color='white').generate(negative_reviews)
fig, ax = plt.subplots()
ax.imshow(wordcloud_negative, interpolation='bilinear')
ax.axis('off')
st.pyplot(fig)

#kesimpulan
st.subheader("Kesimpulan")
st.write("Dashboard ini menunjukkan distribusi skor ulasan, analisis kata kunci dari ulasan positif dan negatif.")